name: Code Quality

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
        
  complexity-analysis:
    name: Code Complexity Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install analysis tools
      run: |
        python -m pip install --upgrade pip
        pip install radon xenon
        
    - name: Analyze code complexity
      run: |
        echo "=== Cyclomatic Complexity ==="
        radon cc services/ -a -nc
        echo "=== Maintainability Index ==="
        radon mi services/ -nc
        echo "=== Raw Metrics ==="
        radon raw services/ -s
        
    - name: Check complexity thresholds
      run: |
        xenon --max-absolute B --max-modules A --max-average A services/
        
  documentation-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install documentation tools
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle interrogate
        
    - name: Check docstring coverage
      run: |
        interrogate services/ -v --ignore-init-method --ignore-magic --ignore-module --ignore-nested-functions --fail-under=80
        
    - name: Check docstring style
      run: |
        pydocstyle services/ --convention=google
